### ISSUE TITLE
token_from_post referenced before assignment

### ISSUE THREAD

**Issue by mybigman** [gnat/csrf-starlette-fastapi#3]
```python
if (str(token_from_cookie) != str(token_from_post)) and (str(token_from_cookie) != str(token_from_header)):
UnboundLocalError: local variable 'token_from_post' referenced before assignment
```
I believe your going to need to find another way to get the post request as I dont believe `request.state` has this, therefore your `token_from_post` is never going to be set.

**Comment by Oluwatooki** [comment]
> ```python
> if (str(token_from_cookie) != str(token_from_post)) and (str(token_from_cookie) != str(token_from_header)):
> UnboundLocalError: local variable 'token_from_post' referenced before assignment
> ```
> 
> I believe your going to need to find another way to get the post request as I dont believe `request.state` has this, therefore your `token_from_post` is never going to be set.

Any Fix for this please?

**Comment by gnat** [comment]
Should be good now.
